name: hw_dashboard_client
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_form_builder: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  form_builder_validators: ^9.1.0
  go_router: ^12.1.3
  intl: ^0.18.0
  meta: ^1.11.0
  shared_preferences: ^2.2.2

  hw_dashboard_domain:
    path: ../hw_dashboard_domain
  syntax_sugar:
    path: ../syntax_sugar

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/presentation/assets/logo.png
    - lib/presentation/assets/logo-short.png

  fonts:
    - family: FangZhengYaHei
      fonts:
        - asset: lib/presentation/assets/fangzhengyahei.ttf